### ISSUE TITLE
docs: Give an example of "ye olde way"

### ISSUE THREAD

**Issue by aleclarson** [FormidableLabs/react-context-composer#18]
Also, are there other libraries attempting to solve the annoyance of nested providers? Curious about other possible design patterns that compelled someone to build them.

**Comment by blainekasten** [comment]
have you heard the news about [_hooks_?](https://formidable.com/blog/2018/hooked-facebook-react/)

**Comment by blainekasten** [comment]
I'm not actually entirely sure what your question is. Are you asking about other libraries that solve this? or why we built this?

**Comment by aleclarson** [comment]
Hooks cannot provide context, AFAIK.

>Are you asking about other libraries that solve this?

Yup! Curious if you're aware of solutions the same problem this library solves.

>..or why we built this?

Nope, I get it. Thanks!

**Comment by aleclarson** [comment]
I guess you _could_ do:
```ts
const Provider = useProviders(
  FooProvider,
  BarProvider,
)

return <Provider> ... </Provider>
```

**Comment by aleclarson** [comment]
Here's a sandbox with a `useProviders` implementation if you're interested.

https://codesandbox.io/s/qrk1zlw86

**Comment by blainekasten** [comment]
Thanks for that! Honestly, I think if hooks land stable this library has less value because the `useContext` hook is really simple to use already. I'll talk internally with other Formidables about the long term value of this library.
