### ISSUE TITLE
Provider composition doesn't work

### ISSUE THREAD

**Issue by motiz88** [FormidableLabs/react-context-composer#8]
`context[i + 1]` should be replaced with `contexts[i + 1]` in the following code:

https://github.com/FormidableLabs/react-context-composer/blob/304233a2acfe2a4b0acc6de463d8ddb3946bc928/src/index.js#L50

I'm happy to PR this along with some tests in a couple of days. In the mean time someone might want to make this ~one-keystroke~ fix and release a patch version.

**Comment by dddom** [comment]
I believe there's a bit more to it, in fact, consider a `reduceRight`... (comment without very deep investigation).

**Comment by alexcanessa** [comment]
There is: in `.reduce((res, context, i)` -  in the first loop - `context` is the second item of the Array (and `i` is `1`).
This means the first context won't be composed.

**Comment by motiz88** [comment]
@dddom @alexcanessa You got me there. Not a one-keystroke fix after all. Looks like adding tests would be doubly important then! 😅
